### ISSUE TITLE
关于asr转录后文本错误问题

### ISSUE THREAD

**Issue by liuyijiang1994** [hahahawu/VCSum#2]
作者您好，这个工作对中文会议摘要相关研究来说非常关键，数据集及相关研究的工作贡献很大！
有个问题想要请教一下，文中提到对转录得到的文本，在100个样本上进行了评估，字级别的错误在8%，并鼓励标注者上报任何发现的错误等。
想请问一下，最终发布的数据中，文本是转录直接得到的，还是经过人工纠错的？或者说部分经过了纠错？
谢谢，期待您的回复！

**Comment by liuyijiang1994** [comment]
此外不知能否提供一下原始video的目录或链接，用于asr相关模型，非常感谢！

**Comment by hahahawu** [comment]
感谢您对我们工作的关注！对于发布数据，该文本大部分均是直接从ASR转录获得，仅经过少量规则清洗以及人工纠错，我们经过细致人工纠错的数据出于公司商业用途，无法公开。文章中的实验数据也是基于目前发布版本的数据进行报告的，且8%的字级别错误也是在目前该发布版本的数据上评测。

video目录我们暂时无法公开，因为还无法确定直接分发原始视频是否存在版权问题。后续等我们确定不存在版权问题后会公开相关video链接或原视频。

谢谢！

**Comment by liuyijiang1994** [comment]
> 感谢您对我们工作的关注！对于发布数据，该文本大部分均是直接从ASR转录获得，仅经过少量规则清洗以及人工纠错，我们经过细致人工纠错的数据出于公司商业用途，无法公开。文章中的实验数据也是基于目前发布版本的数据进行报告的，且8%的字级别错误也是在目前该发布版本的数据上评测。
> 
> video目录我们暂时无法公开，因为还无法确定直接分发原始视频是否存在版权问题。后续等我们确定不存在版权问题后会公开相关video链接或原视频。
> 
> 谢谢！

感谢您的解答！

**Comment by njzheng** [comment]
请问现在有打算开源audio的计划吗？
